[package]
name = "unsaac"
version = "1.1.0"
entrypoint = "unsaac.typ"
authors = ["Daniel A. Sallo <ccusdanielalegriasallo7@gmail.com>"]
license = "MIT"
description = "Mi paquete para la UNSAAC."
repository = "https://github.com/daniel-alegria3/typst-unsaac"
categories = ["thesis"]
keywords = ["unsaac", "tesis", "facultad", "informatica"]
exclude = ["example.*"]

